### ISSUE TITLE
MDS Test API returns 404 on new DOIs

### ISSUE THREAD

**Issue by haarli** [datacite/poodle#30]
Hello,

hope this is the right place for this bug report.

Today we found out, that the MDS Test API GET method https://mds.test.datacite.org/doi/{doi} for newly registered DOIs does not work anymore. It always returns 404 - DOI not found.

**Examples:**
https://mds.test.datacite.org/doi/10.17872/atto.1.1.1 
->404
https://mds.test.datacite.org/doi/10.15771/imejidev.3dg
->404

All these DOIs were created correctly and are also visible in DOI Fabrica Test.
This only happens for DOIs which were created today (30.01.2020).

The DOIs which we created during the last test run (12.01.2020) are still working fine, e.g.:
https://mds.test.datacite.org/doi/10.15771/imejidev.3ao
->200

There haven't been any changes on our side. 

Thank you for any help and hints.

**Comment by richardhallett** [comment]
Hello, thanks for reporting.

This should now be fixed, it wasn't a problem specific to the code, but rather our test handle service that had run out of memory, this was causing none of the DOI's to "register" and the API relies on the handle server to be able to return a URL.

For your specific DOI's created recently, you will need to re-register them and this will make sure they get added to the test handle service.

An on-going fix will require some further infrastructure monitoring to ensure we can catch these types of problems.

**Comment by haarli** [comment]
@richardhallett 
Thank you for the fix and the fast reply. The https://mds.test.datacite.org/doi/{doi}  is now working again for re-registered DOIs

However, we still have another issue, and I'm not sure if this is also related to this problem.
We are using "GET https://mds.test.datacite.org/doi/" to retrieve a list of DOIs from the system. However, this list only contains DOIs from one of our prefixes (10.15771). When we register a DOI with another of our prefixes (10.17872), they are not part of this list. 

Is the method "GET https://mds.test.datacite.org/doi/" for lists deprecated anyway, as I cannot find it in the API documentation anymore?  Or is this another issue or even expected behaviour?

Thanks again.

**Comment by richardhallett** [comment]
Hello, this appears to be a different bug, I've raised an issue to track it here: #31 

Depending on your usecase you can still query your DOI's using our public REST API see 
https://support.datacite.org/docs/api-get-lists

Keeping this closed to continue investigation on #31
